// Generated by CoffeeScript 1.6.2
(function() {
  var fs, md;

  fs = require('fs');

  md = require('node-markdown').Markdown;

  module.exports = function(app) {
    return app.get('/changelog', function(req, res) {
      return fs.readFile('changelog.md', 'utf8', function(err, data) {
        return res.render('md', {
          pageBody: err != null ? err : md(data)
        });
      });
    });
  };

}).call(this);
