// Generated by CoffeeScript 1.6.2
(function() {
  var User, crypto;

  crypto = require('crypto');

  User = require('../core/user');

  exports.login = function(req, res) {
    return res.render('login', {
      title: 'log in'
    });
  };

  exports.doLogin = function(req, res) {
    var md5, password, username;

    if (req.body.passwordAgain !== req.body.password) {
      req.flash('error', "passwords don't match");
      return res.redirect('/register');
    }
    username = req.body.username;
    md5 = crypto.createHash('md5');
    password = md5.update(req.body.password).digest('base64');
    return User.getByName(username, function(err, user) {
      if (user) {
        req.flash('error', "user exists");
        return res.redirect('/register');
      }
      user = new User({
        username: username,
        password: password
      });
      return user.save(function(err) {
        return res.redirect('/');
      });
    });
  };

}).call(this);
