// Generated by CoffeeScript 1.6.2
(function() {
  var ObjectID, RecurringTask, db,
    __hasProp = {}.hasOwnProperty,
    __extends = function(child, parent) { for (var key in parent) { if (__hasProp.call(parent, key)) child[key] = parent[key]; } function ctor() { this.constructor = child; } ctor.prototype = parent.prototype; child.prototype = new ctor(); child.__super__ = parent.prototype; return child; };

  db = require('./Db');

  ObjectID = db.ObjectID;

  /*
  @class RecurringTask
  */


  RecurringTask = (function(_super) {
    __extends(RecurringTask, _super);

    /**
    @field _id {ObjectID}
    @field owner {ObjectID}
    @field firstInstance {ObjectID}
    @field datePattern {DatePattern}
    @field exceptions {Array(Task)}
    */


    function RecurringTask(config) {}

    return RecurringTask;

  })(Task);

}).call(this);
